### ISSUE TITLE
Cards not shown while flipping

### ISSUE THREAD

**Issue by Ashfinn** [DryBoss/match-card#1]
There is a bug where sometimes when an incorrect match happens and the card flips to show what's underneath. It doesn't show anything.

**Comment by DryBoss** [comment]
The loading time of images appears to be extended which creating this issue. Perhaps I should preload all images at the outset. Thank you for your valuable feedback :)

**Comment by Ashfinn** [comment]
If you need help I can contribute... Otherwise you can fix the bug and close this issue.

**Comment by Ashfinn** [comment]
@DryBoss the cards are flipping way too fast now... can't even see the cards

**Comment by DryBoss** [comment]
I have not made any changes since the last issue. It is unclear why you are now experiencing faster card flipping. I believe 350 milliseconds is sufficient.

Thank you for your feedback.
